openapi: "3.0.2"
info:
  title: "techspec demo backend"
  version: "1.00"
servers:
  - url: http://localhost:8085/api
paths:

#  Пользователи
  /subscriptions/users/{id}:
    get:
      summary: Выборка пользователя
      operationId: getUser
      tags:
        - SUBSCRIPTIONS
      parameters:
        - name: id
          description: ИД пользователя
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Пользователь
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userDto"

    patch:
      summary: Изменение пользователя
      operationId: modifyUser
      tags:
        - SUBSCRIPTIONS
      parameters:
        - name: id
          description: ИД пользователя
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userInDto"
      responses:
        200:
          description: Пустой ответ

    delete:
      summary: Удаление пользователя
      operationId: deleteUser
      tags:
        - SUBSCRIPTIONS
      parameters:
        - name: id
          description: ИД пользователя
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Пустой ответ

  /subscriptions/users:
    get:
      summary: Выборка списка пользователей
      operationId: getUsers
      tags:
        - SUBSCRIPTIONS
      responses:
        200:
          description: Список пользователей
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userDtos"
    post:
      summary: Добавление пользователя
      operationId: addUser
      tags:
        - SUBSCRIPTIONS
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userInDto"
      responses:
        200:
          description: Пустой ответ

#  сервисы
  /subscriptions/services/{serviceId}:
    get:
      summary: Выборка сервиса
      operationId: getService
      tags:
        - SUBSCRIPTIONS
      parameters:
        - name: serviceId
          description: ИД сервиса
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Сервис
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/serviceDto"

    patch:
      summary: Изменение сервиса
      operationId: modifyService
      tags:
        - SUBSCRIPTIONS
      parameters:
        - name: serviceId
          description: ИД сервиса
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/serviceInDto"
      responses:
        200:
          description: Пустой ответ

    delete:
      summary: Удаление сервиса
      operationId: deleteService
      tags:
        - SUBSCRIPTIONS
      parameters:
        - name: serviceId
          description: ИД сервиса
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Пустой ответ

  /subscriptions/services:
    post:
      summary: Добавление сервиса
      operationId: addService
      tags:
        - SUBSCRIPTIONS
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/serviceInDto"
      responses:
        200:
          description: Пустой ответ
    get:
      summary: Выборка списка подписок
      operationId: getServices
      tags:
        - SUBSCRIPTIONS
      responses:
        200:
          description: Список сервисов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/serviceDtos"

#   Подписки
  /subscriptions:
    post:
      summary: Добавление подписки
      operationId: addSubscriptions
      tags:
        - SUBSCRIPTIONS
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/subscriptionInDto"
      responses:
        200:
          description: Пустой ответ

    get:
      summary: Выборка списка подписок
      operationId: getSubscriptions
      tags:
        - SUBSCRIPTIONS
      responses:
        200:
          description: Список подписок
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/subscriptionViewDtos"

  /subscriptions/{subscriptionId}:
    patch:
      summary: Изменение подписки
      operationId: modifySubscription
      tags:
        - SUBSCRIPTIONS
      parameters:
        - name: subscriptionId
          description: ИД подписки
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/subscriptionInDto"
      responses:
        200:
          description: Пустое значение
    get:
      summary: Выборка подписки
      operationId: getSubscription
      tags:
        - SUBSCRIPTIONS
      parameters:
        - name: subscriptionId
          description: ИД подписки
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Данные по подписке
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/subscriptionViewDto"
    delete:
      summary: Удаление подписки
      operationId: deleteSubscription
      tags:
        - SUBSCRIPTIONS
      parameters:
        - name: subscriptionId
          description: ИД подписки
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Пустой ответ

components:
  schemas:

    serviceDtos:
      type: array
      description: Список сервисов
      items:
        $ref: "#/components/schemas/serviceDto"
    serviceDto:
      type: object
      description: Сервис
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор сервиса
          example: 1
        name:
          type: string
          description: Наименование сервиса
          example: Наименование сервиса 1

    serviceInDto:
      type: object
      description: Сервис
      properties:
        name:
          type: string
          description: Наименование сервиса
          example: Наименование сервиса 1

    subscriptionDtos:
      type: array
      description: Список подпис ок
      items:
        $ref: "#/components/schemas/subscriptionDto"
    subscriptionDto:
      type: object
      description: Подписка
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор подписки
          example: 1
        name:
          type: string
          description: Наименование подписки
          example: Наименование подписки 1

    subscriptionViewDtos:
      type: array
      description: Список подписок
      items:
        $ref: "#/components/schemas/subscriptionViewDto"
    subscriptionViewDto:
      type: object
      description: Подписка
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        name:
          type: string
          description: Наименование
          example: Наименование  1
        userId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        lastName:
          type: string
          description: Фамилия
          example: Иванов
        firstName:
          type: string
          description: Имя
          example: Имя
        secondName:
          type: string
          description: Отчество
          example: Отчество
        serviceId:
          type: integer
          format: int64
          description: Идентификатор сервиса
          example: 1
        serviceName:
          type: string
          description: Наименование сервиса
          example: Netflix

    subscriptionInDto:
      type: object
      description: Подписка
      properties:
        userId:
          type: integer
          format: int64
          description: Идентификатор пользователя
          example: 1
        serviceId:
          type: integer
          format: int64
          description: Идентификатор сервиса
          example: 1

    userDtos:
      type: array
      description: Список пользователей
      items:
        $ref: "#/components/schemas/userDto"
    userDto:
      type: object
      description: Пользователь
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор записи
          example: 1
        firstName:
          type: string
          description: Имя
          example: Петр
        lastName:
          type: string
          description: Фамилия
          example: Петров
        secondName:
          type: string
          description: Отчество
          example: Петрович
        email:
          type: string
          description: email
          example: email
        phone:
          type: string
          description: phone
          example: +7(916)234-67-89
        telegram:
          type: string
          description: ACCESS_KEY
          example: test

    userInDto:
      type: object
      description: Данные о пользователе
      properties:
        firstName:
          type: string
          description: Имя
          example: Петр
        lastName:
          type: string
          description: Фамилия
          example: Петров
        secondName:
          type: string
          description: Отчество
          example: Петрович
        email:
          type: string
          description: email
          example: email
        phone:
          type: string
          description: phone
          example: +7(916)234-67-89
        telegram:
          type: string
          description: ACCESS_KEY
          example: test
