openapi: "3.0.2"
info:
  title: "techspec demo backend"
  version: "1.00"
servers:
  - url: http://localhost:8085/api
paths:

#  Пользователи
  /users/{id}:
    get:
      summary: Выборка пользователя
      operationId: getUser
      tags:
        - Subscription
      parameters:
        - name: id
          description: ИД пользователя
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Пользователь
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userDto"

    put:
      summary: Изменение пользователя
      operationId: modifyUser
      tags:
        - Subscription
      parameters:
        - name: id
          description: ИД пользователя
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userInDto"
      responses:
        200:
          description: Пустой ответ

    delete:
      summary: Удаление пользователя
      operationId: deleteUser
      tags:
        - Subscription
      parameters:
        - name: id
          description: ИД пользователя
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Пустой ответ

  /users:
    get:
      summary: Выборка списка пользователей
      operationId: getUsers
      tags:
        - Subscription
      responses:
        200:
          description: Список пользователей
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userDtos"
    post:
      summary: Добавление пользователя
      operationId: addUser
      tags:
        - Subscription
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userInDto"
      responses:
        200:
          description: Пустой ответ

#  сервисы
  /services:
    get:
      summary: Выборка списка типов сервисов
      operationId: getServices
      tags:
        - Subscription
      responses:
        200:
          description: Список сервисов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/serviceDtos"

#   Подписки
  /users/{userId}/subscriptions:
    get:
      summary: Выборка списка подписок пользователя
      operationId: getSubscriptions
      tags:
        - Subscription
      parameters:
        - name: userId
          description: ИД пользователя
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Список подписок пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/subscriptionViewDtos"

  /users/{userId}/subscriptions/{serviceId}:
    post:
      summary: Добавление подписки для пользователя
      operationId: addSubscription
      tags:
        - Subscription
      parameters:
        - name: userId
          description: ИД пользователя
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: serviceId
          description: ИД сервиса
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Пустой ответ
    delete:
      summary: Удаление подписки для пользователя
      operationId: deleteSubscription
      tags:
        - Subscription
      parameters:
        - name: userId
          description: ИД подписки
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: serviceId
          description: ИД сервиса
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Пустой ответ

  /subscriptions/top:
    get:
      summary: получить ТОП-3 популярных сервисов
      operationId: getTopServices
      tags:
        - Subscription
      responses:
        200:
          description: Список подписок
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/subscriptionsTopViewDtos"

components:
  schemas:
    serviceDtos:
      type: array
      description: Список сервисов
      items:
        $ref: "#/components/schemas/serviceDto"
    serviceDto:
      type: object
      description: Сервис
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор сервиса
          example: 1
        name:
          type: string
          description: Наименование сервиса
          example: Наименование сервиса 1

    serviceInDto:
      type: object
      description: Сервис
      properties:
        name:
          type: string
          description: Наименование сервиса
          example: Наименование сервиса 1

    subscriptionDtos:
      type: array
      description: Список подпис ок
      items:
        $ref: "#/components/schemas/subscriptionDto"
    subscriptionDto:
      type: object
      description: Подписка
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор подписки
          example: 1
        name:
          type: string
          description: Наименование подписки
          example: Наименование подписки 1

    subscriptionViewDtos:
      type: array
      description: Список подписок
      items:
        $ref: "#/components/schemas/subscriptionViewDto"
    subscriptionViewDto:
      type: object
      description: Подписка
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        userId:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        lastName:
          type: string
          description: Фамилия
          example: Иванов
        firstName:
          type: string
          description: Имя
          example: Имя
        secondName:
          type: string
          description: Отчество
          example: Отчество
        serviceId:
          type: integer
          format: int64
          description: Идентификатор сервиса
          example: 1
        serviceName:
          type: string
          description: Наименование сервиса
          example: Netflix

    subscriptionInDto:
      type: object
      description: Подписка
      properties:
        userId:
          type: integer
          format: int64
          description: Идентификатор пользователя
          example: 1
        serviceId:
          type: integer
          format: int64
          description: Идентификатор сервиса
          example: 1

    subscriptionsTopViewDtos:
      type: array
      description: Список топовых сервисов
      items:
        $ref: "#/components/schemas/subscriptionsTopViewDto"
    subscriptionsTopViewDto:
      type: object
      description: Cервис с указанием количества подписок
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор сервиса
          example: 1
        name:
          type: string
          description: Наименование сервиса
          example: Наименование сервиса 1
        rate:
          type: integer
          format: int64
          description: Количество подписок на сервис
          example: 1

    userDtos:
      type: array
      description: Список пользователей
      items:
        $ref: "#/components/schemas/userDto"
    userDto:
      type: object
      description: Пользователь
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор записи
          example: 1
        firstName:
          type: string
          description: Имя
          example: Петр
        lastName:
          type: string
          description: Фамилия
          example: Петров
        secondName:
          type: string
          description: Отчество
          example: Петрович
        email:
          type: string
          description: email
          example: email
        phone:
          type: string
          description: phone
          example: +7(916)234-67-89
        telegram:
          type: string
          description: ACCESS_KEY
          example: test

    userInDto:
      type: object
      description: Данные о пользователе
      properties:
        firstName:
          type: string
          description: Имя
          example: Петр
        lastName:
          type: string
          description: Фамилия
          example: Петров
        secondName:
          type: string
          description: Отчество
          example: Петрович
        email:
          type: string
          description: email
          example: email
        phone:
          type: string
          description: phone
          example: +7(916)234-67-89
        telegram:
          type: string
          description: ACCESS_KEY
          example: test
